spring.application.name=Textile-eCommerce
spring.datasource.url=jdbc:mysql://localhost:3306/stu
spring.datasource.username=root
spring.datasource.password=admin2
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
# MongoDB connection configuration
spring.data.mongodb.uri=mongodb+srv://chaitanya:mongopass%40123@serverlessinstance0.aopjuua.mongodb.net/ecommerce?retryWrites=true&w=majority


